import Head from 'next/head'
import { useRouter } from 'next/router';
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Button, Flex, Box, Spacer, Heading } from '@chakra-ui/react'
import { MdAdd } from 'react-icons/md'
import { PostDetail } from '@/components/post-detail';
const inter = Inter({ subsets: ['latin'] })

export default function Detail() {
  const router = useRouter();
  const {id} = router.query

  const handleUpdateRedirect = (postId: any) => {
    router.push(`/update/${postId}`);
  };

  return (
    <>
      <Head>
        <title>Detail Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex minWidth='max-content' alignItems='center' gap='2'>
        <Box p='2'>
          <Heading size='md'>Next Imp Test</Heading>
        </Box>
        <Spacer />
        <Button leftIcon={<MdAdd />} colorScheme='teal' variant='solid'  onClick={() => handleUpdateRedirect(id)}>
          Edit Post
        </Button>
      </Flex>
      <main className={`${styles.main} ${inter.className}`}>
        <PostDetail id={Number(id)} />
      </main>
    </>
  )
}
